name: Build Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number of EventStore to base the container off of."
        required: true
        default: ci
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: testdata
          build-args: |
            source_version=${{ github.event.inputs.version }}
      - name: Publish Image
        shell: bash
        run: |
          docker tag testdata ghcr.io/eventstore/testdata:${{ github.event.inputs.version }}
          docker push ghcr.io/eventstore/testdata:${{ github.event.inputs.version }}
