name: Build Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number of EventStore to base the container off of."
        required: true
        default: ci
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: testcontainer
          build-args: |
            source_version=${{ github.event.inputs.version }}-buster-slim